version: '2'

services:
    db:
        image: mysql
        ports:
            - 127.0.0.1:3306:3306
        volumes:
            - ./.data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: MDP2mysql* 
            MYSQL_DATABASE: agisante
            MYSQL_USER: agisante
            MYSQL_PASSWORD: '!MDP2prodV2#'
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
    php:
        build: php7-fpm
        ports:
            - "9000:9000"
            - "10000:10000"
        links:
            - db:mysqldb
            - redis
        volumes:
            - /var/www/oscar:/var/www/oscar
            - /var/www/oscarinfo:/var/www/oscarinfo
            - ./logs/oscar:/var/www/oscar/back/var/logs

    nginx:
        build: nginx
        ports:
            - 80:80
        links:
            - php
            - rabbit
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx

    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx

    rabbit:
        image: "rabbitmq:3-management"
        hostname: "rabbit"
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
          - "15672:15672"
          - "5672:5672"
        labels:
          NAME: "rabbitmq"
        volumes:
          - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"