<?php

/**
 * @category Entities
 * @author   Jean-Loup Empis <jlempis@gmail.com>
 * @version  Release: 2.0.0
 */

namespace Gestime\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AbonneRepondeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonneRepondeurRepository extends EntityRepository
{
    /**
     * [hasRepondeur description]
     * @param Repondeur $repondeur [description]
     * @return boolean            l'abonne à un répondeur d'enregistré
     */
    public function hasRepondeur($repondeur)
    {
        $qb = $this->createQueryBuilder('a')
        ->select('count(a.id)')
        ->where('a.repondeur = :repondeur');

        $qb->setParameter('repondeur', $repondeur);

        return (intval($qb->getQuery()->getSingleScalarResult()) >0);
    }
}
