<?php

namespace Gestime\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
    /**
     * [getAllBySite description]
     * @param  [type] $site [description]
     * @return [type]       [description]
     */
    public function getAllBySite($site)
    {
        $qbCategories = $this->createQueryBuilder('c')
            ->select('c.nom, c.style')
            ->where('c.site = :site')
            ->setParameter('site', $site);

        return $qbCategories->getQuery()->getArrayResult();
    }
}
