<?php

namespace Gestime\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConsigneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsigneRepository extends EntityRepository
{
    /**
     * [getListConsignes description]
     * @return [type] [description]
     */
    public function getListConsignes()
    {
        return $this->createQueryBuilder('c')
        ->select('m.nom as m_nom,
                  p.nom as p_nom,
                  c.idConsigne as c_idConsigne,
                  c.description as c_description ,
                  c.debut as c_debut,
                  c.fin as c_fin,
                  c.bloquante as c_bloquante,
                  c.visible as c_visible')
        ->leftjoin('c.medecin', 'm')
        ->leftjoin('c.patient', 'p');
    }

    /**
     * [getListConsignesBbyPatient description]
     * @param  [type] $idPatient [description]
     * @return [type]            [description]
     */
    public function getListConsignesBbyPatient($idPatient)
    {
        return $this->createQueryBuilder('c')
        ->select('med.nom,
                  p.nom,
                  c.idConsigne,
                  c.description ,
                  c.debut,
                  c.fin,
                  c.bloquante,
                  c.visible')
        ->leftjoin('c.medecin', 'med')
        ->leftjoin('c.patient', 'p')
        ->where('p.id = :idPatient')
        ->setParameter('idPatient', $idPatient);
    }
}
