<?php

namespace Gestime\CoreBundle\Entity;

use Snc\RedisBundle\Doctrine\Cache\RedisCache;
use Predis\Client;
use Doctrine\ORM\EntityRepository;

/**
 * HoraireInternetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoraireInternetRepository extends EntityRepository
{
  /**
   * @param $idMedecin
   * @return array
   */

  public function getHorairesInternetMedecin($idMedecin) {

    $predis = new RedisCache();
    $predis->setRedis(new Client());
    $cache_lifetime = 3600;

    $qb = $this->createQueryBuilder('h')
      ->select('h,parametre')
      ->leftjoin('h.medecin', 'medecin')
      ->leftjoin('h.jour', 'parametre')
      ->where('medecin.idMedecin = :idMedecin')
      ->orderBy('parametre.code')
      ->addOrderBy('h.debut')
      ->setParameter('idMedecin', $idMedecin)
      ->getQuery()
      ->setResultCacheDriver($predis)
      # set cache lifetime
      ->setResultCacheLifetime($cache_lifetime)
      ->getArrayResult();

    //dump($qb);

    return $qb;
  }
}
