<?php

namespace Gestime\CoreBundle\Entity;

use Snc\RedisBundle\Doctrine\Cache\RedisCache;
use Predis\Client;
use Doctrine\ORM\EntityRepository;

/**
 * HoraireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoraireRepository extends EntityRepository {

  /**
   * @param $idMedecin
   * @return array
   */
  public function getHorairesMedecin($idMedecin) {

    $predis = new RedisCache();
    $predis->setRedis(new Client());
    $cache_lifetime = 3600;

    return $this->createQueryBuilder('h')
      ->select('h,parametre')
      ->leftjoin('h.medecin', 'medecin')
      ->leftjoin('h.jour', 'parametre')
      ->where('medecin.idMedecin = :idMedecin')
      ->orderBy('parametre.code')
      ->addOrderBy('h.debut')
      ->setParameter('idMedecin', $idMedecin)
      ->getQuery()
      ->setResultCacheDriver($predis)
      ->setResultCacheLifetime($cache_lifetime)
      ->getArrayResult();
  }
}
