<?php

/**
 * @category Entities
 * @author   Jean-Loup Empis <jlempis@gmail.com>
 * @version  Release: 2.0.0
 */

namespace Gestime\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LigneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneRepository extends EntityRepository
{
    /**
     * [getListLignes description]
     * @param  [type] $site [description]
     * @return [type]       [description]
     */
    public function getListLignes($site)
    {
        $qb = $this->createQueryBuilder('l')
        ->select('l.idLigne as l_idLigne,
                  l.numero as l_numero')
        ->where('l.site = :site')
        ->setParameter('site', $site);

        return $qb;
    }

    /**
     * [getListLignesAll description]
     * @return [type] [description]
     */
    public function getListLignesAll()
    {
        $qb = $this->createQueryBuilder('l')
        ->select('l.numero');

        return $qb;
    }

    /**
     * [getLignesDisponibles description]
     * @param Site   $site
     * @param String $ligneActuelle Numero de la ligne
     * @return querybuilder
     */
    public function getLignesDisponibles($site, $ligneActuelle = null)
    {
        $maintenant = date('Y-m-d H:i:s');

        $qbLignesActives = $this->createQueryBuilder('l')
            ->select('l.idLigne')
            ->leftjoin('l.affectations', 'a')
            ->where('a.debut < :debut');

        $orModule = $qbLignesActives->expr()->orx();
        $orModule->add($qbLignesActives->expr()->gt('a.fin', ':fin'));
        $orModule->add($qbLignesActives->expr()->isNull('a.fin'));
        $qbLignesActives->andWhere($orModule);

        if ($ligneActuelle !== null) {
            $qbLignesActives->andwhere('l.numero <> :ligneActuelle');
        }

        $qbLignesActives->getDQL();

        $qb = $this->createQueryBuilder('li');
        $qb->leftjoin('li.affectations', 'af')
             ->where('li.idLigne NOT IN('.$qbLignesActives.')')
             ->andwhere('li.site = :site')
             ->setParameter('debut', $maintenant)
             ->setParameter('fin', $maintenant)
             ->setParameter('site', $site);
        if ($ligneActuelle !== null) {
            $qb->setParameter('ligneActuelle', $ligneActuelle);
        }
        $qb->orderBy('li.numero', 'ASC');

        return $qb;
    }
}
