<?php

/**
 * @category Entities
 * @author   Jean-Loup Empis <jlempis@gmail.com>
 * @version  Release: 2.0.0
 */

namespace Gestime\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParametreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametreRepository extends EntityRepository
{
    /**
     * [getParamByType description]
     * @param Parametre $param
     * @return querybuilder
     */
    public function getParamByType($param)
    {
        $qbParam = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.type = :param')
            ->orderBy('p.ordre')
            ->setParameter('param', $param);

        return $qbParam;
    }

    /**
     * [getAllParams description]
     * @return querybuilder
     */
    public function getAllParams()
    {
        $qbParam = $this->createQueryBuilder('p')
            ->select('p');

        return $qbParam;
    }

    /**
     * [getParamByTypeAndCode description]
     * @param string $param
     * @param string $code
     * @return querybuilder
     */
    public function getParamByTypeAndCode($param, $code)
    {
        $qbParam = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.type = :param')
            ->andwhere('p.code = :code')
            ->setParameter('param', $param)
            ->setParameter('code', $code);

        return $qbParam;
    }


    /**
     * [getParamByTypeAndValue description]
     * @param  [type] $param [description]
     * @param  [type] $value [description]
     * @return [type]        [description]
     */
    public function getParamByTypeAndValue($param, $value)
    {
        $qbParam = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.type = :param')
            ->andwhere('p.value = :value')
            ->setParameter('param', $param)
            ->setParameter('value', $value);

        return $qbParam;
    }
}
