<?php

/**
 * @category Entities
 * @author   Jean-Loup Empis <jlempis@gmail.com>
 * @version  Release: 2.0.0
 */

namespace Gestime\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RepondeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepondeurRepository extends EntityRepository
{
    /**
     * [isActif description]
     * @param Repondeur $repondeur
     * @return querybuilder
     */
    public function isActif($repondeur)
    {
        $idRepondeur = $repondeur->getIdRepondeur();
        $qbAbonneRepondeur = $this->createQueryBuilder('r')
            ->select('r.idRepondeur')
            ->from('Gestime\CoreBundle\Entity\Fermeture', 'fer')
            ->leftjoin('fer.repondeur', 'rep')
            ->where('rep.idRepondeur = :id')
            ->setParameter('id', $idRepondeur);

        $repondeurActifAbonne = $qbAbonneRepondeur->getQuery()->getResult();

        return $qbAbonneRepondeur;
    }

    /**
     * [getRepondeurByTag description]
     * @param string $tag
     * @return querybuilder
     */
    public function getRepondeurByTag($tag)
    {
        $qbParam = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.tag = :tag')
            ->setParameter('tag', $tag);

        return $qbParam;
    }
}
