<?php

namespace Gestime\CoreBundle\Entity;

/**
 * SousSpecialiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousSpecialiteRepository extends \Doctrine\ORM\EntityRepository
{
}
