<?php

namespace Gestime\CoreBundle\Entity;

/**
 * SpecialiteMedicaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialiteMedicaleRepository extends \Doctrine\ORM\EntityRepository
{
}
