<?php

namespace Gestime\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpecialiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialiteRepository extends EntityRepository
{

  public function getSpecialites()
  {
    return $this->createQueryBuilder('s')
      ->select('s.nom, s.id')
      ->orderBy('s.ordreAffichage')
      ->getQuery()
      ->getArrayResult();
  }

  public function getRaisons($specialite)
  {
    return $this->createQueryBuilder('s')
      ->select('s', 'raisons')
      ->leftJoin('s.raisonRdvs', 'raisons')
      ->where('s.id = :specialite')
      ->setParameter('specialite', $specialite)
      ->getQuery()
      ->getArrayResult();
  }

  public function getUniqueSpecialite()
  {
    return $this->createQueryBuilder('s')
      ->select('s')
      ->where("s.nom <> ''")
      ->groupBy('s.nom')
      ->orderBy('s.ordreAffichage')
      ;
  }


}
