<?php

namespace Gestime\CoreBundle\Entity;

/**
 * TarificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarificationRepository extends \Doctrine\ORM\EntityRepository
{


}
