<?php

namespace Gestime\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleRepository extends EntityRepository
{
    /**
     * [getVillesByCpostal description]
     * @param string $codePostal
     * @return querybuilder
     */
    public function getVillesByCpostal($codePostal)
    {
        return $this->createQueryBuilder('ville')
            ->where('ville.codePostal = :codePostal')
            ->setParameter('codePostal', $codePostal);
    }

    /**
     * [getVillesById description]
     * @param integer $idVille
     * @return querybuilder
     */
    public function getVillesById($idVille)
    {
        return $this->createQueryBuilder('ville')
            ->where('ville.id = :idVille')
            ->setParameter('idVille', $idVille);
    }
}
