parameters:
    gestime_api.event.jwt_response_listener.class: Gestime\ApiBundle\EventListener\JWTResponseListener
    gestime_api.event.jwt_created_listener.class: Gestime\ApiBundle\EventListener\JWTCreatedListener
    gestime_api.event.jwt_decoded_listener.class: Gestime\ApiBundle\EventListener\JWTDecodedListener

services:
    gestime_api.event.jwt_response_listener:
        class: %gestime_api.event.jwt_response_listener.class%
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
    gestime_api.event.jwt_created_listener:
        class: %gestime_api.event.jwt_created_listener.class%
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
    gestime_api.event.jwt_decoded_listener:
        class: %gestime_api.event.jwt_decoded_listener.class%
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onJWTDecoded }
